### ISSUE TITLE
issue running

### ISSUE THREAD

**Issue by jmcouffin** [OliverEGreen/Regular#2]
**Describe the bug**
I get this error everytime I push the **create rule** button

![image](https://user-images.githubusercontent.com/7872003/114847163-b1b9a900-9ddd-11eb-9a06-8e1434775927.png)

**Desktop (please complete the following information):**
 - Revit Version [2021 french and english] none worked

**Comment by jmcouffin** [comment]
interesting tool btw @OliverEGreen. Thanks for sharing

**Comment by OliverEGreen** [comment]
Hi @jmcouffin ! Thanks for the speedy bug report.
Do you have Visual Studio and / or Github Desktop? Happy to arrange a call to debug this with you.

**Comment by jmcouffin** [comment]
cool, caught you on yourdesk U slack hub.

**Comment by jmcouffin** [comment]
3rd restart of revit and visual studio debug attachment and it works
